"use client";
import { useRef,useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowDownToLine, ArrowLeft, ArrowRight, Check, CheckCheck, ChevronLeft, CircleCheck, Clipboard, FileJson, Filter, Inbox, Instagram, Loader2, MessageCircle, MessagesSquare, Plus, Search, Send, Settings2, Sparkles, Upload, X } from "lucide-react";
import { analyzeConversation } from "@/lib/analyze";
import { KEYS, useStored, uid } from "@/lib/store";
import { Conversation, Profile } from "@/lib/types";
import { EXAMPLE_THREADS, InboxChannel, InboxThread, inboxText, parseInboxFile } from "@/lib/inbox";
import type { Analysis } from "@/lib/schemas";
import {OBJECTION_LABELS} from "@/lib/schemas";

const channels:Record<InboxChannel,string>={instagram:"Instagram",messenger:"Messenger",whatsapp:"WhatsApp (demo)",web:"Web / import"};
function ChannelIcon({channel}:{channel:InboxChannel}) {return channel==="instagram"?<Instagram size={14}/>:channel==="messenger"?<MessagesSquare size={14}/>:<MessageCircle size={14}/>}
export default function InboxPage(){
 const [threads,setThreads,ready]=useStored<InboxThread[]>("prodvisor.inbox.v3",EXAMPLE_THREADS);
 const [analyses,setAnalyses]=useStored<Record<string,Analysis>>("prodvisor.inbox.analyses.v3",{});
 const [convs,setConvs]=useStored<Conversation[]>(KEYS.conversations,[]);
 const [profile]=useStored<Profile|null>(KEYS.profile,null);
 const [selected,setSelected]=useState<string>(EXAMPLE_THREADS[0].id);
 const [filter,setFilter]=useState<"all"|"unread"|"open">("all"),[channel,setChannel]=useState<"all"|InboxChannel>("all"),[search,setSearch]=useState(""),[draft,setDraft]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[mobile,setMobile]=useState<"list"|"thread"|"analysis">("list");
 const file=useRef<HTMLInputElement>(null);
 const current=threads.find(t=>t.id===selected)||threads[0];
 const visible=threads.filter(t=>(filter==="all"||(filter==="unread"&&t.unread)||(filter==="open"&&t.status==="open"))&&(channel==="all"||t.channel===channel)&&(t.customer.toLocaleLowerCase().includes(search.toLocaleLowerCase())||t.messages.some(m=>m.text.toLocaleLowerCase().includes(search.toLocaleLowerCase()))));
 const latest=current?.messages.at(-1);
 function pick(id:string){setSelected(id);setMobile("thread");setError("");setThreads(p=>p.map(t=>t.id===id?{...t,unread:false}:t));}
 function reply(){if(!draft.trim()||!current)return;setThreads(ts=>ts.map(t=>t.id===current.id?{...t,messages:[...t.messages,{id:uid(),from:"business",text:draft.trim(),at:new Date().toLocaleTimeString('az-AZ',{hour:'2-digit',minute:'2-digit'})}]}:t));setDraft("");}
 function toggleStatus(){if(!current)return;setThreads(ts=>ts.map(t=>t.id===current.id?{...t,status:t.status==='open'?'closed':'open'}:t));}
 async function analyze(){if(!current||busy)return;setBusy(true);setError("");try{const out=await analyzeConversation(inboxText(current),profile);setAnalyses(p=>({...p,[current.id]:out.analysis}));const c:Conversation={id:`inbox-${current.id}`,title:`${current.customer} · ${channels[current.channel]}`,text:inboxText(current),createdAt:new Date().toISOString(),status:"done",analysis:out.analysis,meta:out.meta,synthetic:!!current.synthetic};setConvs(p=>[c,...p.filter(x=>x.id!==c.id)]);setMobile("analysis");}catch(e){setError(e instanceof Error?e.message:"Analiz alınmadı.");}finally{setBusy(false)}}
 async function importFile(f?:File){if(!f)return;setError("");try{if(f.size>1_000_000)throw new Error("Fayl 1 MB-dan böyük olmamalıdır.");const parsed=parseInboxFile(JSON.parse(await f.text()));setThreads(p=>[...parsed,...p]);if(parsed[0])pick(parsed[0].id);file.current!.value="";}catch(e){setError(e instanceof Error?e.message:"Faylı oxumaq mümkün olmadı.");}}
 function template(){const data=[{customer:"Müştəri A",channel:"instagram",messages:[{from:"customer",text:"Salam, məhsulun qiyməti nə qədərdir?",at:"10:01"},{from:"business",text:"Salam, 45 AZN-dir.",at:"10:02"}]}];const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download="prodvisor-inbox-import-example.json";a.click();URL.revokeObjectURL(url);}
 if(!ready)return <div className="skeleton h-[65vh] rounded-3xl"/>;
 return <div className="inbox-page -mx-3 -mt-3 sm:-mx-5 lg:-mx-4 lg:-mt-4"><div className="mb-5 flex flex-wrap items-center justify-between gap-3 px-1"><div><span className="label-eyebrow">CUSTOMER INTELLIGENCE</span><h1 className="mt-2 font-display text-[30px] font-extrabold tracking-[-.05em]">Vahid inbox<span className="text-accent">.</span></h1><p className="mt-2 text-xs text-muted">Mesajları bir yerdə gör, AI ilə analiz et, daha yaxşı cavab ver.</p></div><div className="flex items-center gap-2"><button onClick={template} className="inbox-toolbar-btn"><ArrowDownToLine size={15}/> JSON nümunə</button><input type="file" accept="application/json,.json" ref={file} onChange={e=>importFile(e.target.files?.[0])} className="hidden"/><button className="inbox-toolbar-btn" onClick={()=>file.current?.click()}><Upload size={15}/> Import et</button><Link href="/integrations" className="inbox-toolbar-btn !bg-ink !text-white"><Settings2 size={15}/> Kanalları bağla</Link></div></div>
 {error&&<div className="mb-4 flex items-center justify-between gap-3 rounded-xl border border-[#F2DADD] bg-[#FFF5F5] p-3 text-xs text-[#9C3753]"><span><AlertTriangle size={14} className="mr-2 inline"/>{error}</span><button onClick={()=>setError("")} aria-label="Xətanı bağla"><X size={15}/></button></div>}
 <div className="mb-3 flex gap-2 lg:hidden"><button onClick={()=>setMobile('list')} className={`inbox-mobile-tab ${mobile==='list'?'inbox-mobile-on':''}`}>Siyahı</button><button onClick={()=>setMobile('thread')} className={`inbox-mobile-tab ${mobile==='thread'?'inbox-mobile-on':''}`}>Söhbət</button><button onClick={()=>setMobile('analysis')} className={`inbox-mobile-tab ${mobile==='analysis'?'inbox-mobile-on':''}`}>AI nəticəsi</button></div>
 <div className="inbox-layout">
 <aside className={`inbox-list ${mobile!=='list'?'inbox-mobile-hidden':''}`}><div className="border-b border-line p-4"><div className="flex items-center justify-between gap-2"><h2 className="font-display text-[15px] font-extrabold">Söhbətlər <span className="ml-1 text-muted">{threads.length}</span></h2><span className="rounded-full bg-[#F0ECFB] px-2 py-1 text-[10px] font-bold text-accent">Demo / Import</span></div><div className="relative mt-4"><Search size={16} className="absolute left-3 top-3 text-[#92899E]"/><input aria-label="Söhbətlərdə axtar" className="form-control !min-h-10 !pl-9 !text-xs" placeholder="Müştəri və ya mesaj..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="mt-3 flex gap-1.5">{([['all','Hamısı'],['unread','Oxunmamış'],['open','Açıq']] as const).map(([k,name])=><button key={k} onClick={()=>setFilter(k)} className={`rounded-lg px-3 py-2 text-[11px] font-bold ${filter===k?'bg-[#EEE7FD] text-accent':'text-muted hover:bg-[#F5F2F9]'}`}>{name}</button>)}</div><select aria-label="Kanal filtri" value={channel} onChange={e=>setChannel(e.target.value as typeof channel)} className="form-control mt-3 !min-h-9 !text-xs"><option value="all">Bütün kanallar</option>{Object.entries(channels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="inbox-list-scroll">{visible.length?visible.map(t=><button key={t.id} onClick={()=>pick(t.id)} className={`inbox-thread-item ${selected===t.id?'inbox-thread-active':''}`}><span className="inbox-avatar">{t.customer.slice(0,1)}</span><span className="min-w-0 flex-1 text-left"><span className="flex items-center justify-between gap-2"><span className="truncate text-[12px] font-extrabold">{t.customer}</span>{t.unread&&<span className="h-2 w-2 shrink-0 rounded-full bg-accent"/>}</span><span className="mt-1 flex items-center gap-1 text-[10px] font-semibold text-[#93899F]"><ChannelIcon channel={t.channel}/>{channels[t.channel]} {t.synthetic?' · Demo':''}</span><span className="mt-1.5 block truncate text-[11px] text-muted">{t.messages.at(-1)?.text}</span></span></button>):<p className="p-5 text-xs leading-6 text-muted">Bu filtr üzrə yazışma yoxdur.</p>}</div><div className="border-t border-line px-4 py-3 text-[10px] leading-5 text-muted">Yazışmalar yalnız bu brauzerdə saxlanır. Meta hesabları hələ bağlı deyil.</div></aside>
 <section className={`inbox-conversation ${mobile!=='thread'?'inbox-mobile-hidden':''}`}>{current?<><div className="flex items-center justify-between gap-2 border-b border-line bg-white px-5 py-4"><div className="flex items-center gap-3"><span className="inbox-avatar">{current.customer[0]}</span><div><h2 className="text-[13px] font-extrabold">{current.customer}</h2><p className="mt-1 flex items-center gap-1 text-[10px] text-muted"><ChannelIcon channel={current.channel}/> {channels[current.channel]} · {current.synthetic?'Demo söhbət':'İmport edilmiş'}</p></div></div><button onClick={toggleStatus} className="inline-flex items-center gap-1 rounded-lg border border-line px-2.5 py-2 text-[10px] font-bold"><CircleCheck size={14}/>{current.status==='open'?'Bağla':'Aç'}</button></div><div className="inbox-chat-scroll"><div className="mx-auto max-w-[630px] space-y-5 py-5"><div className="text-center text-[10px] text-[#A49BAC]">{current.synthetic?'Təlim məqsədli sintetik yazışma':'İmport edilmiş yazışma'} · {channels[current.channel]}</div>{current.messages.map(m=><div key={m.id} className={`flex ${m.from==='business'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] rounded-2xl px-4 py-3 text-[12px] leading-6 ${m.from==='business'?'rounded-br-sm bg-[#E9E0FE] text-[#3C2E62]':'rounded-bl-sm border border-line bg-white text-ink'}`}>{m.text}<span className="mt-1 block text-right text-[10px] text-[#9489A2]">{m.at}</span></div></div>)}</div></div><div className="border-t border-line bg-white px-4 py-4"><p className="mb-2 text-[10px] text-muted">{current.synthetic?'Demo rejimi — mesaj göndərilmir':'İmport edilmiş söhbət — cavab yalnız lokal olaraq əlavə olunur'}</p><div className="flex items-end gap-2"><textarea aria-label="Cavab yaz" rows={2} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Cavabınızı yazın..." className="form-control !min-h-14 resize-none !text-xs"/><button onClick={reply} disabled={!draft.trim()} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-accent text-white disabled:opacity-40" title="Yalnız demo cavabı əlavə et"><Send size={18}/></button></div><button onClick={()=>setMobile('analysis')} className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-accent lg:hidden">AI analizinə keç <ArrowRight size={14}/></button></div></>:<div className="p-8 text-sm text-muted">Söhbət seçin.</div>}</section>
 <aside className={`inbox-ai ${mobile!=='analysis'?'inbox-mobile-hidden':''}`}><div className="flex items-center justify-between gap-2 border-b border-line px-5 py-4"><h2 className="flex items-center gap-2 text-[13px] font-extrabold"><Sparkles size={18} className="text-accent"/> Prodvisor AI</h2><span className="rounded-full bg-[#F1EBFC] px-2 py-1 text-[10px] font-bold text-accent">Context aware</span></div><div className="inbox-ai-scroll px-5 py-5">{current? <>{analyses[current.id]?<><span className="label-eyebrow">ANALİZ NƏTİCƏSİ</span><h3 className="mt-3 text-lg font-extrabold leading-snug">{analyses[current.id].summary}</h3><div className="mt-5 space-y-3">{analyses[current.id].objections.slice(0,3).map((o,i)=><div className="rounded-xl border border-line bg-white p-3" key={i}><span className="text-xs font-extrabold">{OBJECTION_LABELS[o.type]}</span><p className="mt-2 border-l-2 border-accent pl-3 text-[11px] leading-6 text-muted">“{o.evidence}”</p></div>)}</div><div className="mt-5 rounded-2xl bg-[#F3EEFC] p-4"><p className="text-xs font-extrabold text-accent">Təklif edilən cavab</p><p className="mt-3 whitespace-pre-line text-[12px] leading-7 text-[#5E546E]">{analyses[current.id].suggestedReply}</p><button className="mt-4 inline-flex items-center gap-1 rounded-lg bg-white px-3 py-2 text-xs font-bold text-accent" onClick={()=>navigator.clipboard?.writeText(analyses[current.id].suggestedReply)}><Clipboard size={14}/> Kopyala</button></div><Link href={`/customers/inbox-${current.id}`} className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-accent">Tam analizə bax <ArrowRight size={14}/></Link></>:<div className="py-10 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-[#EEE7FD] text-accent"><Sparkles size={28}/></div><h3 className="mt-5 font-display text-[19px] font-extrabold">Söhbəti analiz edək?</h3><p className="mx-auto mt-3 max-w-[260px] text-[12px] leading-7 text-muted">Müştərinin ehtiyacını, mümkün etirazlarını və növbəti cavabı öyrənin.</p></div>}<button disabled={busy} onClick={analyze} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-accent px-4 py-3.5 text-xs font-extrabold text-white transition hover:bg-accent-dark disabled:opacity-60">{busy?<Loader2 size={17} className="animate-spin"/>:<Sparkles size={16}/>} {busy?'AI analiz edir...':analyses[current.id]?'Yenidən analiz et':'Bu söhbəti analiz et'}</button><p className="mt-4 text-[11px] leading-6 text-muted">Nəticə yalnız dialoqda görünən məlumatlara əsaslanır. Müştərinin niyyəti barədə nəticələr ehtimal ola bilər.</p></>:<p className="text-xs text-muted">Analiz üçün söhbət seçin.</p>}</div></aside>
 </div></div>;
}
