"use client";
import {useState} from "react";
import {ArrowRight,Bookmark,Check,ClipboardCopy,Lightbulb,Megaphone,Plus,RefreshCw,Sparkles,Target,Trash2} from "lucide-react";
import {Profile} from "@/lib/types";
import {KEYS,useStored,uid} from "@/lib/store";
import {postJSON} from "@/lib/api";
import {Button,Card,Empty,ErrorNote,PageHeader,Spinner} from "@/components/ui";
type Campaign={id:string;title:string;objective:string;plan:string;createdAt:string};
export default function CampaignsPage(){const [profile,,ready]=useStored<Profile|null>(KEYS.profile,null);const [saved,setSaved]=useStored<Campaign[]>("prodvisor.campaigns",[]);const [objective,setObjective]=useState("sales"),[channel,setChannel]=useState("Instagram"),[budget,setBudget]=useState(""),[details,setDetails]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState(""),[copied,setCopied]=useState(false);
 const objectives:Record<string,string>={sales:"Satışları artırmaq",awareness:"Brend tanınması",leads:"Yeni müraciətlər toplamaq",retention:"Mövcud müştəriləri geri qaytarmaq"};
 async function generate(){if(!profile)return;setBusy(true);setError("");try{const prompt=`${profile.name} biznesi üçün kampaniya planı hazırla. Bu real biznesin məlumatlarıdır: Məhsul: ${profile.product}; auditoriya: ${profile.audience}; dəyər təklifi: ${profile.valueProp}; məqsəd: ${profile.goals}; çətinlik: ${profile.challenges}; qiymət: ${profile.pricing}. Kampaniya hədəfi: ${objectives[objective]}, kanal: ${channel}, büdcə: ${budget.trim()||"qeyd edilməyib"}, əlavə istək: ${details||"yoxdur"}. Yalnız Azərbaycan dilində konkret, icra edilə bilən, qısa kampaniya brifi yaz. Bölmələr: kampaniya adı, məqsəd və auditoriya, əsas mesaj, təklif/CTA, 3 kontent fikri, bir həftəlik ilkin test planı, real ölçülə bilən KPI. Əgər rəqəm/tarif verilməyibsə uydurma; hər tövsiyəni hipotez kimi göstər. Ümumi klişelərdən qaç.`;const out=await postJSON<{reply:string}>("/api/ai/advisor",{messages:[{role:"user",content:prompt}],profile,insights:""});setResult(out.reply);}catch(e){setError(e instanceof Error?e.message:"Plan hazırlana bilmədi");}finally{setBusy(false);}}
 function save(){if(!result)return;setSaved(p=>[{id:uid(),title:`${objectives[objective]} · ${channel}`,objective,plan:result,createdAt:new Date().toISOString()},...p]);}
 if(!ready)return <div className="skeleton h-52 rounded-2xl"/>;if(!profile)return <><PageHeader title="Kampaniyalar"/><Empty title="Kampaniya üçün əvvəlcə biznesinizi tanıyaq" text="AI planınız məhsul, auditoriya və biznes məqsədlərinizə uyğun olsun." action={<Button href="/onboarding">Biznesimi tanıt <ArrowRight size={16}/></Button>}/></>;
 return <div className="space-y-6"><PageHeader eyebrow="GROWTH STUDIO" title="Kampaniyanızı birlikdə planlayaq." sub="Məhsulunuza və auditoriyanıza uyğun ideyaları, mesajları və test planını bir yerdə hazırlayın."/>
 <div className="grid items-start gap-5 lg:grid-cols-[.82fr_1.18fr]"><Card><div className="mb-5 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#F1EBFD] text-accent"><Megaphone size={20}/></span><div><h2 className="font-display text-[16px] font-extrabold">Yeni kampaniya</h2><p className="mt-0.5 text-xs text-muted">Dörd sadə addımla başlayın.</p></div></div><label className="text-[12px] font-bold">1. Kampaniyanın məqsədi</label><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(objectives).map(([key,label])=><button key={key} onClick={()=>setObjective(key)} aria-pressed={objective===key} className={`min-h-[62px] rounded-xl border p-3 text-left text-[12px] font-semibold transition ${objective===key?"border-accent bg-[#F5F0FF] text-accent-dark":"border-line bg-white hover:border-[#C7B7EE]"}`}>{label}</button>)}</div><label className="mt-5 block text-[12px] font-bold" htmlFor="platform">2. Əsas platforma</label><select id="platform" value={channel} onChange={e=>setChannel(e.target.value)} className="form-control mt-2"><option>Instagram</option><option>TikTok</option><option>Facebook</option><option>Google Ads</option><option>E-mail</option><option>Çoxkanallı</option></select><label className="mt-5 block text-[12px] font-bold" htmlFor="budget">3. Büdcə <span className="font-normal text-muted">(istəyə bağlı)</span></label><input id="budget" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Məsələn, 150 AZN / həftə" className="form-control mt-2"/><label className="mt-5 block text-[12px] font-bold" htmlFor="details">4. Xüsusi istəyiniz <span className="font-normal text-muted">(istəyə bağlı)</span></label><textarea id="details" value={details} onChange={e=>setDetails(e.target.value)} placeholder="Hansı məhsulu önə çıxarmaq istəyirsiniz?" rows={3} className="form-control mt-2 resize-y"/><div className="mt-5 flex items-start gap-2 rounded-xl bg-[#F9F6FC] px-3.5 py-3"><Target size={16} className="mt-0.5 shrink-0 text-accent"/><p className="text-[11px] leading-6 text-muted">AI planı <strong>{profile.name}</strong> biznesinizin Business DNA məlumatlarından istifadə edəcək.</p></div>{error&&<div className="mt-3"><ErrorNote>{error}</ErrorNote></div>}<Button onClick={generate} disabled={busy} className="mt-5 w-full"><Sparkles size={16}/> {busy?"Hazırlanır...":"Kampaniya planı yarat"}<ArrowRight size={15}/></Button></Card>
 <div className="space-y-4"><div className="soft-gradient rounded-[20px] border border-[#E9DFFA] p-6"><div className="flex items-center gap-2 text-xs font-bold text-accent-dark"><Sparkles size={16}/> Prodvisor Growth Studio</div><h2 className="mt-3 font-display text-xl font-extrabold">Hər kampaniya bir məqsədlə başlayır.</h2><p className="mt-2 text-[13px] leading-6 text-muted">Aydın hədəf seçin, AI təklifini öz biznesinizə uyğunlaşdırın və nəticəni test edin.</p></div>
 {busy?<Card className="!py-16 text-center"><Spinner label="Biznesinizə uyğun strategiya hazırlanır..."/></Card>:result?<Card><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="font-display text-lg font-extrabold">Sizin kampaniya planınız</h2><span className="rounded-full bg-[#ECF8EE] px-3 py-1 text-[11px] font-bold text-good">AI tərəfindən hazırlandı</span></div><article className="whitespace-pre-wrap rounded-xl bg-[#FAF9FB] p-5 text-[13px] leading-[2]">{result}</article><div className="mt-5 flex flex-wrap gap-2"><Button onClick={save}><Bookmark size={15}/> Planı yadda saxla</Button><Button variant="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(result);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{}}}><ClipboardCopy size={15}/> {copied?"Kopyalandı":"Kopyala"}</Button><Button variant="ghost" disabled={busy} onClick={generate}><RefreshCw size={14}/> Yenilə</Button></div></Card>:<Card className="!py-12 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#F1EBFD] text-accent"><Lightbulb size={26}/></span><h2 className="mt-5 font-display text-[18px] font-extrabold">Yeni ideyalar burada görünəcək</h2><p className="mx-auto mt-2 max-w-sm text-xs leading-6 text-muted">Soldakı sahələri doldurun. AI sizin üçün mesaj, kontent istiqaməti və ölçmə planı hazırlayacaq.</p></Card>}</div></div>
 {saved.length>0&&<section><h2 className="mb-4 font-display text-[17px] font-extrabold">Yadda saxlanılan planlar ({saved.length})</h2><div className="grid gap-3 md:grid-cols-2">{saved.map(c=><Card key={c.id}><div className="flex items-start justify-between gap-3"><div><p className="text-[13px] font-extrabold">{c.title}</p><p className="mt-1 text-[11px] text-muted">{new Date(c.createdAt).toLocaleDateString("az-AZ")}</p></div><button className="icon-btn !h-8 !w-8 hover:text-bad" onClick={()=>{if(window.confirm("Planı silmək istəyirsiniz?"))setSaved(p=>p.filter(x=>x.id!==c.id))}} aria-label="Planı sil"><Trash2 size={15}/></button></div><p className="mt-3 line-clamp-3 text-xs leading-6 text-muted">{c.plan}</p><Button variant="secondary" className="mt-4" onClick={()=>{setResult(c.plan);window.scrollTo({top:0,behavior:"smooth"})}}>Planı aç <ArrowRight size={14}/></Button></Card>)}</div></section>}</div>;
}
