"use client";
import Link from "next/link";
import {ArrowRight,ArrowUpRight,Check,CheckCircle2,ChevronRight,ClipboardList,Clock3,Fingerprint,Lightbulb,MessageCircleMore,Plus,Sparkles,Target,TrendingUp} from "lucide-react";
import {ActionItem,Conversation,Profile} from "@/lib/types";
import {KEYS,uid,useStored} from "@/lib/store";
import {OBJECTION_LABELS,PRIORITY_LABELS} from "@/lib/schemas";
import {doneConversations,objectionCounts,topRecommendations,unansweredList} from "@/lib/insights";
import {Badge,Button,Card,Empty,PageHeader,SectionHeader} from "@/components/ui";
export default function Dashboard(){
 const [profile,,ready]=useStored<Profile|null>(KEYS.profile,null);const [convs]=useStored<Conversation[]>(KEYS.conversations,[]);const [actions,setActions]=useStored<ActionItem[]>(KEYS.actions,[]);
 if(!ready)return <div className="space-y-5"><div className="skeleton h-16 rounded-2xl"/><div className="skeleton h-56 rounded-2xl"/></div>;
 if(!profile)return <><PageHeader eyebrow="XOŞ GƏLMİSİNİZ" title="Biznesinizin yeni başlanğıcı." sub="Bir neçə suala cavab verin. Prodvisor biznesinizi tanısın və sizə özəl məsləhətlər hazırlasın."/><div className="grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(0,.65fr)]"><div className="soft-gradient rounded-[24px] border border-[#E8DFFA] p-8 sm:p-11"><span className="inline-flex items-center gap-2 rounded-full bg-white/80 px-3 py-1.5 text-xs font-bold text-accent-dark"><Sparkles size={14}/> Şəxsi AI məsləhətçiniz</span><h2 className="mt-7 max-w-lg font-display text-3xl font-extrabold leading-[1.18] sm:text-[38px]">Məhsulunuzu tanıyaq.<br/><span className="text-accent">Sonra birlikdə böyüdək.</span></h2><p className="mt-4 max-w-md leading-7 text-muted">Nə satdığınızı, müştərilərinizin kim olduğunu və hansı məqsədə çatmaq istədiyinizi öyrənərək başlayırıq.</p><Button href="/onboarding" className="mt-7">Biznesimi tanıt <ArrowRight size={16}/></Button></div><Card className="flex flex-col justify-center"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-accent-soft text-accent"><Fingerprint size={25}/></div><h3 className="font-display text-xl font-extrabold">Business DNA nədir?</h3><p className="mt-3 text-sm leading-7 text-muted">Biznesinizin məhsulu, fərqləri, auditoriyası və məqsədlərindən ibarət şəxsi profili. AI hər cavabını bu məlumata əsaslandırır.</p><Link href="/onboarding" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-accent-dark">Başlamağa hazıram <ArrowRight size={16}/></Link></Card></div></>;
 const done=doneConversations(convs);const objections=objectionCounts(convs);const unanswered=unansweredList(convs);const recs=topRecommendations(convs,3);const primary=recs[0];const pending=Object.values(profile.status).filter(x=>x==="needs_review").length;const open=actions.filter(a=>a.status!=="done");const latest= [...convs].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,3);
 const add=(r:typeof primary)=>{if(!r||actions.some(a=>a.title===r.title&&a.sourceConversationId===r.convId))return;setActions(p=>[{id:uid(),title:r.title,problem:r.problem,recommendation:r.recommendation,priority:r.priority,effort:r.effort,impact:r.expectedImpactHypothesis,status:"todo",note:"",sourceConversationId:r.convId,createdAt:new Date().toISOString()},...p])};
 return <div className="space-y-6 sm:space-y-8">
  <PageHeader eyebrow="SİZİN İŞ SAHƏNİZ" title="Biznesinizə daha aydın baxın." sub={`${profile.name} üçün son məlumatlar, müştəri siqnalları və növbəti addımlar — bir yerdə.`} right={<Button href="/customers"><Plus size={16}/> Söhbəti analiz et</Button>}/>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1.05fr)_minmax(0,.95fr)]">
   <Card className="relative overflow-hidden !p-6 sm:!p-7"><div className="pointer-events-none absolute -right-14 -top-14 h-44 w-44 rounded-full bg-[#F6F2FF] blur-2xl"/><div className="relative"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#F2ECFF] text-accent"><Fingerprint size={18}/></span><span className="text-[12px] font-bold text-muted">Sizin biznesiniz</span></div><Badge tone={pending?"warn":"good"}>{pending?`${pending} məlumatı yoxlayın`:"Profil hazırdır"}</Badge></div><h2 className="mt-5 font-display text-[22px] font-extrabold">{profile.name}</h2><p className="mt-1 line-clamp-2 max-w-[520px] text-[13px] leading-6 text-muted">{profile.product}</p><div className="mt-5 grid gap-4 border-t border-line pt-4 sm:grid-cols-2"><div><span className="label-eyebrow">Hədəf auditoriya</span><p className="mt-1 line-clamp-2 text-[13px] font-semibold">{profile.audience||"Dəqiqləşdirilməyib"}</p></div><div><span className="label-eyebrow">Biznes məqsədi</span><p className="mt-1 line-clamp-2 text-[13px] font-semibold">{profile.goals||"Dəqiqləşdirilməyib"}</p></div></div><Link href="/business" className="mt-5 inline-flex items-center gap-2 text-[13px] font-bold text-accent-dark">Biznes DNA-nı aç <ArrowRight size={16}/></Link></div></Card>
   <div className="soft-gradient relative flex flex-col justify-between overflow-hidden rounded-[20px] border border-[#E8DFFA] p-6 sm:p-7"><div className="pointer-events-none absolute -right-10 -top-10 h-40 w-40 rounded-full border-[22px] border-white/35"/><div className="relative"><span className="inline-flex items-center gap-2 text-[12px] font-extrabold text-accent-dark"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/80"><Sparkles size={17}/></span> Sizin növbəti addımınız</span><h2 className="mt-4 max-w-lg font-display text-[23px] font-extrabold leading-snug">{primary?primary.title:done.length?"AI məsləhətçinizlə strategiyanızı qurun":"İlk müştəri yazışmanızı analiz edin"}</h2><p className="mt-2 line-clamp-3 max-w-lg text-[13px] leading-6 text-[#716681]">{primary?primary.recommendation:done.length?"Biznesiniz və müştəri məlumatlarınız əsasında növbəti böyümə addımlarını müəyyənləşdirin.":"Yazışmadakı sualları, satış maneələrini və inkişaf imkanlarını konkret sübutlarla görə bilərsiniz."}</p></div><Button className="relative mt-5 self-start" href={primary?`/customers/${primary.convId}`:done.length?"/advisor":"/customers"}>{primary?"Tövsiyəni araşdır":done.length?"AI məsləhətçiyə keç":"Analizə başla"}<ArrowRight size={16}/></Button></div>
  </div>
  <section className="grid gap-3 sm:grid-cols-3"><Link href="/customers" className="surface-card group flex items-center gap-4 p-5 transition hover:border-[#CFC0F5]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#F1EDFE] text-accent"><MessageCircleMore size={20}/></div><div><p className="text-[11px] font-semibold text-muted">Analiz edilmiş söhbətlər</p><p className="mt-1 font-display text-[25px] font-extrabold">{done.length}</p></div><ArrowUpRight className="ml-auto text-[#B9ADC5] group-hover:text-accent" size={16}/></Link><Link href="/customers" className="surface-card group flex items-center gap-4 p-5 transition hover:border-[#CFC0F5]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#FFF5E8] text-[#AE762D]"><MessageCircleMore size={20}/></div><div><p className="text-[11px] font-semibold text-muted">Cavabsız müştəri sualları</p><p className="mt-1 font-display text-[25px] font-extrabold">{unanswered.length}</p></div><ArrowUpRight className="ml-auto text-[#B9ADC5] group-hover:text-accent" size={16}/></Link><Link href="/actions" className="surface-card group flex items-center gap-4 p-5 transition hover:border-[#CFC0F5]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#EAF7EF] text-[#2D8866]"><ClipboardList size={20}/></div><div><p className="text-[11px] font-semibold text-muted">Açıq tapşırıqlar</p><p className="mt-1 font-display text-[25px] font-extrabold">{open.length}</p></div><ArrowUpRight className="ml-auto text-[#B9ADC5] group-hover:text-accent" size={16}/></Link></section>
  <section className="grid gap-4 xl:grid-cols-[minmax(0,1.05fr)_minmax(0,.95fr)]"><Card><SectionHeader title="Son müştəri yazışmaları" href="/customers"/>{latest.length? <div className="divide-y divide-line">{latest.map((c,i)=><Link href={`/customers/${c.id}`} key={c.id} className="group flex items-center gap-3 py-3.5 first:pt-0 last:pb-0"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${i%2?"bg-[#F2F4FC] text-[#6C74C4]":"bg-[#F2ECFF] text-accent"}`}><MessageCircleMore size={18}/></span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-bold">{c.title}</p><p className="mt-0.5 truncate text-xs text-muted">{c.analysis?.summary||c.text.replace(/\n/g," ")}</p></div><div className="flex shrink-0 items-center gap-2">{c.synthetic&&<Badge>Demo</Badge>}<ChevronRight className="text-[#B5ACBF] group-hover:text-accent" size={16}/></div></Link>)}</div>:<div className="rounded-xl bg-[#FAF9FB] px-4 py-8 text-center"><MessageCircleMore size={25} className="mx-auto text-[#A79AB6]"/><p className="mt-3 text-sm font-semibold">Hələ analiz yoxdur</p><p className="mt-1 text-xs text-muted">İlk dialoqu əlavə edərək müştərilərinizi daha yaxından tanıyın.</p><Button href="/customers" variant="secondary" className="mt-4">Söhbət əlavə et</Button></div>}</Card>
   <Card><SectionHeader title="Müştərilər sizə nə deyir?" href="/customers" label="Ətraflı bax"/>{objections.length? <div className="space-y-4">{objections.slice(0,4).map((o,i)=>{const max=Math.max(1,...objections.map(x=>x.n));return <div key={i}><div className="mb-2 flex items-center justify-between gap-2"><span className="text-[13px] font-semibold">{OBJECTION_LABELS[o.type]}</span><span className="text-xs font-bold text-muted">{o.n} söhbət</span></div><div className="h-2 overflow-hidden rounded-full bg-[#F2EFF5]"><div className="h-full rounded-full bg-accent" style={{width:`${o.n/max*100}%`,opacity:1-i*.12}}/></div></div>})}<p className="border-t border-line pt-3 text-xs leading-5 text-muted">Bu müşahidələr yalnız daxil etdiyiniz {done.length} analiz edilmiş söhbətə əsaslanır.</p></div>:<div className="flex h-[200px] flex-col items-center justify-center rounded-xl bg-[#FBFAFC] px-5 text-center"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#F0EBFB] text-accent"><Lightbulb size={23}/></span><p className="mt-3 text-sm font-semibold">İlk insight sizi gözləyir</p><p className="mt-1 text-xs leading-5 text-muted">Söhbətlər analiz edildikcə təkrarlanan müştəri ehtiyacları burada görünəcək.</p></div>}</Card></section>
  <section><SectionHeader title="Tez başla"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{href:"/inbox",icon:MessageCircleMore,title:"Vahid inbox",desc:"Mesajları bir yerdə gör və analiz et"},{href:"/advisor",icon:Sparkles,title:"AI-dən məsləhət al",desc:"Biznesinizə özəl cavablar"},{href:"/campaigns",icon:Lightbulb,title:"Kampaniya planla",desc:"Yeni satış ideyaları"},{href:"/actions",icon:CheckCircle2,title:"Fəaliyyət planı",desc:"Tövsiyələri icra et"}].map(({href,icon:Icon,title,desc})=><Link href={href} key={href} className="surface-card group flex items-center gap-3 p-4 transition hover:-translate-y-0.5 hover:border-[#D5C8F0] hover:shadow-soft"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#F4EFFB] text-accent"><Icon size={18}/></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{title}</p><p className="mt-0.5 truncate text-[11px] text-muted">{desc}</p></div><ArrowUpRight size={15} className="text-[#B7ADC4] group-hover:text-accent"/></Link>)}</div></section>
 </div>;
}
