"use client";
import {useState} from "react";
import {AlertTriangle,ArrowRight,Check,CheckCircle2,Clipboard,Copy,Lightbulb,MessageCircleMore,Plus,ShieldAlert,ShieldCheck,Sparkles,Target,TriangleAlert} from "lucide-react";
import {CONF_LABELS,INTENT_LABELS,OBJECTION_LABELS,PRIORITY_LABELS,STAGE_LABELS} from "@/lib/schemas";
import type {ActionItem,Conversation} from "@/lib/types";
import {Badge,Button,Card} from "./ui";
export default function AnalysisView({conv,actions,onAddAction}:{conv:Conversation;actions:ActionItem[];onAddAction:(a:NonNullable<Conversation["analysis"]>["recommendedActions"][number])=>void}){
 const a=conv.analysis!,meta=conv.meta,[copied,setCopied]=useState(false);const missing=new Set(meta?.evidence.missing??[]);const added=(title:string)=>actions.some(x=>x.title===title&&x.sourceConversationId===conv.id);
 const evidence=(text:string)=>!text?.trim()?null:<div className="mt-2 rounded-xl border-l-[3px] border-[#AA8EF1] bg-[#F7F3FD] px-3.5 py-3"><p className="text-[12px] leading-6">“{text}”</p><p className={`mt-2 flex items-center gap-1 text-[10px] font-semibold ${missing.has(text)?"text-warn":"text-good"}`}>{missing.has(text)?<ShieldAlert size={12}/>:<ShieldCheck size={12}/>} {missing.has(text)?"Sitat dialoqda tapılmadı":"Dialoqda doğrulandı"}</p></div>;
 return <div className="space-y-4"><div className="rounded-[20px] border border-[#DED0F7] bg-[#F7F2FF] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-2"><span className="inline-flex items-center gap-2 text-[12px] font-extrabold text-accent-dark"><Sparkles size={17}/> AI-nin ümumi nəticəsi</span><Badge tone="accent">Business DNA ilə təhlil</Badge></div><h2 className="mt-4 font-display text-lg font-extrabold leading-snug">{a.summary}</h2><div className="mt-4 flex flex-wrap gap-2"><Badge tone="accent">Niyyət: {INTENT_LABELS[a.intent]}</Badge><Badge tone="accent">Mərhələ: {STAGE_LABELS[a.journeyStage]}</Badge>{a.objections.length? a.objections.map((o,i)=><Badge tone="warn" key={i}>{OBJECTION_LABELS[o.type]} etirazı</Badge>):<Badge>Etiraz yoxdur</Badge>}</div>{meta&&<p className="mt-4 text-[11px] leading-5 text-muted">Analiz müddəti: {(meta.ms/1000).toFixed(1)} san · Sitatların {meta.evidence.found}/{meta.evidence.total}-i dialoqda tapılıb{meta.maskedCount?` · ${meta.maskedCount} həssas məlumat maskalanıb`:""}.</p>}</div>
 {a.objections.length>0&&<Card><div className="mb-4 flex items-center gap-2"><AlertTriangle size={18} className="text-[#AE7933]"/><h3 className="font-display text-[16px] font-extrabold">Aşkar edilən müştəri etirazları</h3></div><div className="space-y-4">{a.objections.map((o,i)=><div key={i} className="border-b border-line pb-4 last:border-0 last:pb-0"><div className="flex flex-wrap items-center gap-2"><p className="text-[13px] font-bold">{OBJECTION_LABELS[o.type]}</p><Badge tone={o.confidence==="high"?"good":o.confidence==="medium"?"accent":"warn"}>Etibarlılıq: {CONF_LABELS[o.confidence]}</Badge></div>{evidence(o.evidence)}</div>)}</div></Card>}
 <Card><div className="mb-4 flex items-center gap-2"><Target size={18} className="text-accent"/><h3 className="font-display text-[16px] font-extrabold">Satış söhbətinin qiymətləndirilməsi</h3></div><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-xs font-extrabold text-good">Nə yaxşı edildi?</p><ul className="mt-3 space-y-2">{a.sellerAnalysis.didWell.length?a.sellerAnalysis.didWell.map((v,i)=><li className="flex gap-2 text-[12px] leading-6" key={i}><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-good"/>{v}</li>):<li className="text-xs text-muted">Qeyd yoxdur.</li>}</ul></div><div><p className="text-xs font-extrabold text-[#9F6D21]">Nəyi yaxşılaşdırmaq olar?</p><ul className="mt-3 space-y-2">{[...a.sellerAnalysis.tooGeneric,...a.sellerAnalysis.missedOpportunities].length?[...a.sellerAnalysis.tooGeneric,...a.sellerAnalysis.missedOpportunities].map((v,i)=><li className="flex gap-2 text-[12px] leading-6" key={i}><Lightbulb className="mt-1 h-4 w-4 shrink-0 text-[#AD7F36]"/>{v}</li>):<li className="text-xs text-muted">Qeyd yoxdur.</li>}</ul></div></div>{a.sellerAnalysis.unanswered.length>0&&<div className="mt-5 rounded-xl bg-[#FFF8ED] p-4"><p className="text-xs font-extrabold text-warn">Cavabsız qalan suallar</p>{a.sellerAnalysis.unanswered.map((u,i)=><div className="mt-3" key={i}><p className="text-[13px] font-semibold">{u.question}</p>{evidence(u.evidence)}</div>)}</div>}</Card>
 {a.possibleIssues.length>0&&<Card><div className="mb-4 flex items-center gap-2"><TriangleAlert size={18} className="text-[#A97A34]"/><h3 className="font-display text-[16px] font-extrabold">Mümkün problemlər və səbəblər</h3></div><div className="space-y-3">{a.possibleIssues.map((p,i)=><div key={i} className="rounded-xl border border-line p-4"><div className="flex flex-wrap gap-2"><p className="text-[13px] font-bold">{p.issue}</p><Badge tone={p.confidence==="high"?"good":p.confidence==="medium"?"accent":"warn"}>{CONF_LABELS[p.confidence]}</Badge></div>{evidence(p.evidence)}<p className="mt-3 text-xs leading-6 text-muted"><strong className="text-ink">Başqa mümkün izah: </strong>{p.alternativeExplanation}</p><p className="mt-1 text-xs leading-6 text-muted"><strong className="text-ink">Tövsiyə: </strong>{p.recommendedStep}</p></div>)}</div></Card>}
 {a.lostSaleReason&&<Card><h3 className="font-display text-[15px] font-extrabold">Satışın mümkün baş tutmama səbəbi</h3><div className="mt-2 flex flex-wrap items-center gap-2"><p className="text-[13px] leading-6">{a.lostSaleReason.reason}</p>{a.lostSaleReason.isSpeculative&&<Badge tone="warn">Yalnız ehtimal</Badge>}</div>{evidence(a.lostSaleReason.evidence)}<p className="mt-3 text-xs text-muted">Müştərinin həqiqi qərarını təsdiqləmədən bunu qəti səbəb saymaq olmaz.</p></Card>}
 <Card className="!border-[#DCD1F5]"><div className="mb-4 flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#F2ECFF] text-accent"><MessageCircleMore size={17}/></span><h3 className="font-display text-[16px] font-extrabold">Təklif edilən cavab</h3></div><p className="whitespace-pre-wrap rounded-xl bg-[#F7F4FC] px-4 py-4 text-[13px] leading-7">{a.suggestedReply}</p><div className="mt-4 flex flex-wrap items-center gap-3"><Button onClick={async()=>{try{await navigator.clipboard.writeText(a.suggestedReply);setCopied(true);setTimeout(()=>setCopied(false),1900)}catch{setCopied(false)}}}><Copy size={15}/> {copied?"Kopyalandı":"Cavabı kopyala"}</Button><p className="text-[11px] text-muted">Mesaj avtomatik göndərilmir. Göndərməzdən əvvəl yoxlayın.</p></div></Card>
 <Card><div className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Lightbulb size={18} className="text-accent"/><h3 className="font-display text-[16px] font-extrabold">Növbəti addımlar</h3></div><Badge tone="accent">{a.recommendedActions.length} tövsiyə</Badge></div><div className="space-y-3">{a.recommendedActions.map((r,i)=><div key={i} className="rounded-xl border border-[#EDE8F2] bg-white p-4"><div className="flex flex-wrap items-center gap-2"><p className="text-[13px] font-bold">{r.title}</p><Badge tone={r.priority==="high"?"bad":r.priority==="medium"?"warn":"neutral"}>{PRIORITY_LABELS[r.priority]} prioritet</Badge></div><p className="mt-2 text-[12px] leading-6 text-muted">{r.recommendation}</p><p className="mt-1 text-[11px] leading-5 text-muted"><strong>Gözlənilən təsir (hipotez): </strong>{r.expectedImpactHypothesis}</p><div className="mt-3">{added(r.title)?<Badge tone="good"><Check size={13}/> Fəaliyyət planına əlavə edilib</Badge>:<Button variant="secondary" className="!min-h-9 !px-3 !text-xs" onClick={()=>onAddAction(r)}><Plus size={14}/> Plana əlavə et</Button>}</div></div>)}</div></Card>
 </div>;
}
